stages:

  load_data:
    cmd: python service/data/data_load.py data/raw/
    deps:
      - service/data/data_load.py
    outs:
      - data/raw/kion_train

#  prepare_dataset:
#    cmd: python service/data/prepare_datasets.py data/raw/
#    deps:
#      - data/raw/
#      - service/data/prepare_datasets.py
#    outs:
#      - data/processed/train.csv
#      - data/processed/test.csv

#  train:
#    cmd: python src/modelss/train.py  data/processed/train.csv data/processed/test.csv modelss/model.clf
#    deps:
#      - data/processed/train.csv
#      - data/processed/test.csv
#      - src/modelss/train.py
#    outs:
#      - modelss/model.clf
